[project]
name = "backend"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.111.0",
    "uvicorn[standard]==0.30.1",
]

[build-system]
requires      = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
